### ISSUE TITLE
Create documentation for mirroring repos

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/data-science-workflows#11]
As a member of the aicoe-aiops org I want to have my repo mirrored in gitlab so that we can share our work with the rest of Red Hat without granting individual access to the private repos in this org. 

Success Criteria:

- [ ] Document a process that all members can use to mirror their repos in gitlab

- [ ] All existing repos are mirrored

**Comment by MichaelClifford** [comment]
There have been some attempts from other team members to create a pull mirror from github to gitlab that appear to be unsuccessful. It looks like the cause of this is due to that feature being unavailable in the community edition of gitlab 

![image](https://user-images.githubusercontent.com/4494906/85887401-bb721180-b7b5-11ea-9979-582a014375a8.png)

Since we only have the community edition of gitlab we will have to find another way to mirror our repos.

**Comment by MichaelClifford** [comment]
Maybe we could use the method outlined [here](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/duplicating-a-repository#mirroring-a-repository-in-another-location), to create mirrors and keep them up to date.

```
git clone --mirror https://github.com/exampleuser/repository-to-mirror.git
cd repository-to-mirror.git 
git remote set-url --push origin https://github.com/exampleuser/mirrored
git fetch -p origin
git push --mirror
```

The main issue with this appraoch is we would either need to updated the mirrors regularly manually, or set it as a cron job somewhere.

**Comment by tumido** [comment]
Can we make one of the bots do it?

**Comment by MichaelClifford** [comment]
I went ahead and mirrored the [project-template](https://gitlab.cee.redhat.com/aicoe-aiops/project-template) in gitlab using the instructions above into our [aicoe-aiops](https://gitlab.cee.redhat.com/aicoe-aiops) org. It seems to work as intended. I'll go ahead and make some documentation on how to set up the mirror. 


But once its set up, I'm not sure how to proceed with keeping it up to date. I wrote a small cron job to update the mirror every hour as an option, but I think that is probably generally a bad way to do this for our team. To @tumido 's point, Yes :smiley:  This feels like something bots should do. Who can we reach out to about adding this ability to one of the bots? or would this be too specific of a use-case ( only our team needs updated mirrors on gitlab) to have it included in a bot's abilities?    

@durandom what do you think?

**Comment by MichaelClifford** [comment]
work in progress doc :https://docs.google.com/document/d/1ePaTRzf7alVgkSoRa8h-tD6u3rAeoNllp3WBkTo5D-I/edit

**Comment by durandom** [comment]
I'm asking around. ManageIQ and RH Insights have something similar in place

**Comment by tumido** [comment]
Interesting discussion started around this on the GitLab-CEE mailing list (unfortunately the archives are private, so I can't link it here)

Few other new options surfaced:
1) Request access to https://gitlab.corp.redhat.com - This is a enterprise instance of GitLab that can do the mirroring, disadvantage is that all internal users would need to request access to this instance just to read the repo anyways
2) Mirror to [Gerrit](https://code.engineering.redhat.com/gerrit/) - automated mirroring can be requested via [Service Now](https://redhat.service-now.com/help?id=sc_cat_item&sys_id=0e654ba513356600196f7e276144b09e)

**Comment by MichaelClifford** [comment]
It looks like the ManageIQ team opensourced their mirroring script [here](https://github.com/ManageIQ/manageiq-release/blob/master/lib/manageiq/release/git_mirror.rb)

It looks like a ruby script, which I'm not that familiar with, @tumido or @martinpovolny, do you think this is something we could repurposed easily enough for our org's needs?

**Comment by durandom** [comment]
Unfortunately gerrit does not have notebook rendering: https://www.gerritcodereview.com/plugins.html

**Comment by durandom** [comment]
I secured an account on gitlab.corp and setup mirroring of https://gitlab.corp.redhat.com/aicoe-aiops/ocp4-anomaly-detection

Got to do this for other repos as well

**Comment by MichaelClifford** [comment]
@durandom looks like our projects are already mirrored [here](https://gitlab.corp.redhat.com/aicoe-aiops?page=1). Can this issue be closed or is there more to do?

**Comment by MichaelClifford** [comment]
Our projects are already mirrored automatically mirrored to [gitlab](https://gitlab.corp.redhat.com/aicoe-aiops?page=1) . Closing issue.
