### ISSUE TITLE
Add list of current AI Ops projects with short description on DS Workflow Git Repo

### ISSUE THREAD

**Issue by oindrillac** [aicoe-aiops/data-science-workflows#14]
As a non-AIOps team member, I would like to get visibility into ongoing AIOps projects so that efforts are not repeated.

Acceptance Criteria:
* Added a PR to the DS Workflow Repo with list of currently active AIOps projects and a short description to each

**Comment by aakankshaduggal** [comment]
@aicoe-aiops/team-aiops 

We have created a list of active projects with short description. Please review this [doc](https://docs.google.com/document/d/14FsQz-goxgLD1NjOrxmvahc-lasElkgWp19_1YxUcug/edit#).

**Comment by oindrillac** [comment]
@aakankshaduggal I'm hoping the team has got a chance to review this doc by now. I think we should be good to add a PR for this doc
