### ISSUE TITLE
PR review documentation 

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/data-science-workflows#18]
As a reviewer I would like to have well defined guidelines to follow when performing code reviews so that the quality of accepted PR's is relatively standardized across projects. In addition, we need to insure these guidelines take into account the specific needs of data science projects, like the use of jupyter notebooks, reproducible experiments, clear explainability, etc. 

Acceptance Criteria:

- [ ] A Document added to this repo that provides guidelines for performing a PR review on a data science project.

**Comment by MichaelClifford** [comment]
Since we have started to do more Notebook reviews over the last few months, I have noticed that they are often large brand new notebooks that can take a number of revisions before being considered "acceptable" and merged. This can make it difficult to determine what has changed from round to round and over time may require a re-review of the entire notebook. 

I suggest that we adopt a more liberal acceptance policy for newer notebooks. That way we may have one large and rough notebook merged initially, but followed by a series of more smaller and more focused PR's.

**Comment by tumido** [comment]
Maybe we can initially rather put notebooks in some staging folder within the `notebooks` folder? So it's obvious they are "WIP" and after that move them to the parent folder? And with every such notebook let's have an issue "to move the notebook" assigned to the author of it, so we can track and get the notebooks to proper shape eventually - so we don't forget about them? WDYT?

**Comment by MichaelClifford** [comment]
@tumido :+1: I think that's a good idea. My biggest concern with this "liberal" merge policy was that rough work would not get properly updated and update to-do tasks would get lost. But I think having a "stage" directory and issues to move should help to mitigate those issues.
