### ISSUE TITLE
Hosting Public Data 

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/data-science-workflows#19]
As maintainers of multiple opensource data science projects, we need a solution for hosting our public dataset to prevent individual repos from including the data itself. Instead they should only maintain a data collection script that downloads data from the hosted environment.   

Acceptance Criteria: 

- [x] Decide on hosting platform
- [ ] Create documentation for using public hosting platform for our public data sets

**Comment by chauhankaranraj** [comment]
@aicoe-aiops/team-aiops Hey team, does anyone have any ideas or opinions regarding this issue? I think there might be a few possible options here:
1. Use a public facing s3 bucket
2. Use git lfs within each repo
3. Host data on kaggle (similar to some [thoth datasets](https://www.kaggle.com/thothstation/datasets))

wdyt?

**Comment by 4n4nd** [comment]
Kaggle seems like the easiest option to me. Do we have a public facing s3 bucket?

**Comment by MichaelClifford** [comment]
Is it possible to set up an S3 bucket in Ceph so that only our team as Write/Delete access but no credentials are needed for Read?

**Comment by 4n4nd** [comment]
> Is it possible to set up an S3 bucket in Ceph so that only our team as Write/Delete access but no credentials are needed for Read?

It should be possible if we have a public facing s3 bucket

**Comment by MichaelClifford** [comment]
Using a ceph bucket will keep things more in line with the operate first mission, I think. But if there are significant blockers to that, maybe kaggle is the way to go for now?

**Comment by chauhankaranraj** [comment]
> It should be possible if we have a public facing s3 bucket

I'm not sure if we have one (maybe the DH team can confirm? @anishasthana). Should we create a bucket for hosting datasets then?

**Comment by 4n4nd** [comment]
I think the general public might have a better idea on how to access data from kaggle compared to S3. 

The only reasons I can think for using S3 are,
1. Better Analytics for us
2. No dataset size limits

**Comment by MichaelClifford** [comment]
@4n4nd Those seem like good reasons to use ceph :smiley:

**Comment by anishasthana** [comment]
When you say public-facing, would this access include for non Red Hatters?

**Comment by MichaelClifford** [comment]
@anishasthana Correct, public as in anyone.

**Comment by anishasthana** [comment]
hmm, DH Ceph instance is locked behind VPN unfortunately... There are plans to have some sort of ceph instance on the MOC -- would that be a good place to host your data instead?

**Comment by chauhankaranraj** [comment]
> hmm, DH Ceph instance is locked behind VPN unfortunately... There are plans to have some sort of ceph instance on the MOC -- would that be a good place to host your data instead?

I think that'd be a good idea. @durandom thoughts?

**Comment by durandom** [comment]
Yes, we should host data either here on GH (if it's small enough) or on MOC via operate first.
