### ISSUE TITLE
publish content of this repo to the op1st site

### ISSUE THREAD

**Issue by durandom** [aicoe-aiops/data-science-workflows#21]
this involves converting all google docs linked here into .md files.
like https://docs.google.com/document/d/1CIFlKiVbNX3CKC-tD7kVDkP1S8eDfDEibdLM6jgIj2g/edit#

**Comment by MichaelClifford** [comment]
:+1: @durandom Ill start working on this today

**Comment by MichaelClifford** [comment]
I think this issue can be closed. See content on [Operate-First site](https://www.operate-first.cloud/data-science/data-science-workflows/)
