### ISSUE TITLE
Possibly incorrect image in Create and Deploy JH Image guide

### ISSUE THREAD

**Issue by chauhankaranraj** [aicoe-aiops/data-science-workflows#26]
Hey team, in [this section](https://github.com/aicoe-aiops/data-science-workflows/blob/master/docs/create_and_deploy_jh_image.md#setting-up-the-image-repository) of the `create_and_deploy_jh_image.md` guide, the screenshots showing steps 2 and 3 seem to be the exact same. Was the second screenshot supposed to be [this one](https://github.com/aicoe-aiops/data-science-workflows/blob/master/public/assets/jh_image_howto/quay-secret-cred.png) instead?

**Comment by chauhankaranraj** [comment]
cc @martinpovolny

**Comment by tumido** [comment]
You're right @chauhankaranraj, it should indeed point to the image you've linked to! Would you like to submit a PR fixing it? :pray: :+1:

**Comment by chauhankaranraj** [comment]
> You're right @chauhankaranraj, it should indeed point to the image you've linked to! Would you like to submit a PR fixing it?

Yeah sure :+1:
