### ISSUE TITLE
Ascii doc for the blog for DS Workflow

### ISSUE THREAD

**Issue by aakankshaduggal** [aicoe-aiops/data-science-workflows#3]

**Comment by aakankshaduggal** [comment]
https://github.com/aicoe-aiops/data-science-workflows/pull/4#issue-435254351

**Comment by MichaelClifford** [comment]
@aakankshaduggal can you please add a description with acceptance criteria to this issue?

**Comment by MichaelClifford** [comment]
closed via #4
