### ISSUE TITLE
Add data visualization best practices

### ISSUE THREAD

**Issue by hemajv** [aicoe-aiops/data-science-workflows#33]
In https://github.com/aicoe-aiops/ocp-ci-analysis/issues/218 and https://github.com/aicoe-aiops/ocp-ci-analysis/issues/217, we evaluated various visualization tools and python libraries suitable to meet our data viz needs. Based on our choice of tool/library, we should include guidelines and best practices to follow while creating data visualizations within our notebooks as part of our DS project workflow. This will help us to maintain and standardize our visualizations across projects.

**Comment by amsaparov** [comment]
Google doc outline/draft for data visualization practices:
https://docs.google.com/document/d/1zQJAmr5BWN-ZdzRcMIynZTFMAfWV69wFWt56JcVPdOU/edit?usp=sharing

@aakankshaduggal @hemajv

**Comment by aakankshaduggal** [comment]
Thanks for creating this. We will add to this doc. @amsaparov :+1:

**Comment by hemajv** [comment]
@amsaparov the doc looks great! :smile: thank you for adding all the suggestions/changes, do we have an incoming PR for the doc to be added to the repo?
