### ISSUE TITLE
Make changes to PR Review Guidelines

### ISSUE THREAD

**Issue by aakankshaduggal** [aicoe-aiops/data-science-workflows#34]
- [ ] We would like to make generic PR review guidelines and emphasize that our list is targeted to data scientists.
- [ ] Also, to make it more attractive and interesting for our fellow Data Scientists, we will now call it "10 Principles for Reviewing Data Science Code"

References :
https://thoughtbot.com/playbook/developing/code-reviews
https://github.com/thoughtbot/guides/tree/main/code-review

**Comment by MichaelClifford** [comment]
What does it mean to make the guidelines "more generic" and also "targeted to data scientists"? I think they are fairly generic at the moment. Is the goal here to make them more generic, or to make them more specific to data science work? Can you clarify this please?

It might also help to include what the current problem with the existing guidelines is, to guide what the discussion on what kinds of changes are needed to address the problem.  

Also, what are the acceptance criteria for this issue? Rename doc to "10 Principles for Reviewing Data Science Code"? Submit an updated edition of the doc that re-writes the existing principals to be more generic?

**Comment by aakankshaduggal** [comment]
> It might also help to include what the current problem with the existing guidelines is, to guide what the discussion on what kinds of changes are needed to address the problem.

So, we don't have any major problems with the existing guidelines. But Marcel suggested if we could make it more catchy and suitable for our Espresso Series as well. Making it "10 Principles for Reviewing Data Science Code" would make it more attractive to the users and slight reframing of the same so that it can help us "target Data Scientists" better. I hope this answers your questions :)
