### ISSUE TITLE
Re-organize Data Science Workflows

### ISSUE THREAD

**Issue by amsaparov** [aicoe-aiops/data-science-workflows#36]
The current data science workflow section on the website needs to be updated and reorganized as also described in [EPIC] Re-org data science projects (https://github.com/operate-first/operate-first.github.io/issues/265) and in #25 . The goal is to make it more clear, and also consistent with other parts of the website. 

Acceptance Criteria:

- [ ] Update formatting/structure to this:

Data Science Workflows
1. Overview
2. Get Started
3. How to Contribute
4. Data Science Projects

- [ ] Re-organize content within sections to best fit this structure so it is clear and accessible

**Comment by margarethaley** [comment]
Update: we're currently working on these updates in a google doc, which is available [here](https://docs.google.com/document/d/1EhPuGC2lcLsicVfjCHsz7eQsIYJO7OMKQMeF5udgyhw/edit#heading=h.8v67k0jrit3k).
