### ISSUE TITLE
Prepare new Data Science Workflows for review

### ISSUE THREAD

**Issue by margarethaley** [aicoe-aiops/data-science-workflows#39]
This issue is related to https://github.com/aicoe-aiops/data-science-workflows/issues/36.

@amsaparov and I are working together to improve the data science workflows. We've made some improvements to the content already, but wanted to create this issue as a sub-task to help track our progress. We're currently working out of this [google doc](https://docs.google.com/document/d/1EhPuGC2lcLsicVfjCHsz7eQsIYJO7OMKQMeF5udgyhw/edit) and need to get it in shape for review from data scientists. We'll need this review to answer some questions we have and make sure that the updated workflows are both accurate and clear.

Acceptance Criteria:

- [x] completed draft in google doc form
- [x] draft is shared with some data scientists to get feedback and help us fill in gaps where information is missing

**Comment by amsaparov** [comment]
@aakankshaduggal @oindrillac Margaret and I have completed a draft for the data science workflows. We left some comments on the doc, and we would also appreciate any other feedback you may have. The doc is linked in the issue above.

**Comment by MichaelClifford** [comment]
:+1:  Great updates :smiley: 

Just added a few suggested edits/ comments. Let me know if you have any questions or disagree with any of the comments : )
