### ISSUE TITLE
Add examples of issues to DS workflows

### ISSUE THREAD

**Issue by margarethaley** [aicoe-aiops/data-science-workflows#41]
This is another sub-issue of https://github.com/aicoe-aiops/data-science-workflows/issues/36, which @amsaparov and I are working on.

We want to select some examples of good issues to supplement the new Data Science Workflows "Get Started" guide under the "Create a Project Board and Issues" heading. For now, you can find this WIP guide in google doc form [here](https://docs.google.com/document/d/1EhPuGC2lcLsicVfjCHsz7eQsIYJO7OMKQMeF5udgyhw/edit#heading=h.z8it2iccabl
). Adding in these examples will encourage those working on data science projects to create good, consistent issues.

Acceptance Criteria:

- [ ] select a few examples that would be helpful/understandable for someone getting started on a data science project
- [ ] add screenshots of the issues directly into the guide for reference

**Comment by MichaelClifford** [comment]
stale, is a sub-issue of a closed #36
