### ISSUE TITLE
Video and slide examples for DS workflows

### ISSUE THREAD

**Issue by margarethaley** [aicoe-aiops/data-science-workflows#42]
Another sub-issue of #36 w/ @amsaparov:

In updating the Data Science Workflows, we want to include any helpful resources, videos, and tutorials so that people can benefit from them. Therefore, we want to make sure we add a link to @Shreyanand's video on monitoring workloads using grafana dashboards once it's completed.

Additionally, @oindrillac provided us with some examples of deliverables to link. However, it seems there may not be any slide decks that are available for non-Red Hatters to view. We should consider whether we want to link a slide deck that only Red Hatters can view, keep looking for a public slide deck, or leave it without an example. 

Acceptance Criteria:

- [ ] add the new video
- [ ] decide on slide deck and add/update the guide as necessary

**Comment by MichaelClifford** [comment]
stale, sub-issue of closed #36
