### ISSUE TITLE
Add superset and trino best practices to Data Visualization best practices.

### ISSUE THREAD

**Issue by aakankshaduggal** [aicoe-aiops/data-science-workflows#44]

**Comment by MichaelClifford** [comment]
@hemajv @aakankshaduggal is there an existing trino/superset demo on the youtube channel we could link for this issue?

**Comment by aakankshaduggal** [comment]
> @hemajv @aakankshaduggal is there an existing trino/superset demo on the youtube channel we could link for this issue?

Hey @MichaelClifford. We have this demo video - https://youtu.be/ZgWzgdBNMu8

**Comment by MichaelClifford** [comment]
closed by #90
