### ISSUE TITLE
Publish using Github Pages

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/data-science-workflows#54]
We want to publish this jupyterbook by leveraging github pages. Please follow the documentation [here](https://jupyterbook.org/start/publish.html#publish-your-book-online-with-github-pages) to publish our book with ghp-import tool. This will create a new branch on our repo (gh-pages) where the rendered book files will be stored.

**Comment by aakankshaduggal** [comment]
This repository is now available as a JupyterBook - https://aicoe-aiops.github.io/data-science-workflows/README.html
