### ISSUE TITLE
Update link to video and guide to create jupyterhub images

### ISSUE THREAD

**Issue by oindrillac** [aicoe-aiops/data-science-workflows#63]
Link to guide in [creating-jupyterhub-images](https://github.com/aicoe-aiops/data-science-workflows/blob/master/docs/getting-started.md#creating-jupyterhub-images) section in the Getting Started document is incorrect. 

- [ ]  Update it to [correct link](https://www.operate-first.cloud/hitchhikers-guide/data-science-workflows/docs/create_and_deploy_jh_image.md).

**Comment by MichaelClifford** [comment]
This will be addressed by #84 via removing this creating-jupyterhub-images section from the getting started doc.
