### ISSUE TITLE
Template repo not found

### ISSUE THREAD

**Issue by sophwats** [aicoe-aiops/data-science-workflows#8]
Template repo not found in [README.md](https://github.com/aicoe-aiops/data-science-workflows/blob/master/README.md) 
"Create a CookieCutter formatted data science project from this template repo. Follow these instructions to create a new repo from this template."

**Comment by tumido** [comment]
@sophwats it says "not found" because it's a private template now. @durandom do you think there's anything blocking us from making that template repo public? I think there's nothing sensitive in there but I think your opinion is required on this.🙂

**Comment by durandom** [comment]
no, make all public that does not container PII data

**Comment by durandom** [comment]
It's public
